version: '3'
services:
  app:
    container_name: todo-app-go
    build:
      context: .
      dockerfile: ./docker/app/go/Dockerfile
    volumes:
      - type: bind
        source: ../backend/src
        target: go/src
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    container_name: todo-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${password}
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      # - db-store:/docker-entrypoint-initdb.d
      - type: volume
        source: todo-app-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d
      # - db-store:/var/lib/postgresql/data
      # - ./data:/var/lib/postgresql/data

volumes:
  todo-mysql-data: